import Head from 'next/head'
import { ChangeEventHandler, FormEventHandler, useState } from 'react'

export default function Home() {
  const [zipCode, setZipCode] = useState('')
  const [address, setAddress] = useState('')

  const validationErrorMessage = '郵便番号は7桁の数字で入力してください'
  const isValidZipCode = /\d{7}/.test(zipCode)

  const handleChange: ChangeEventHandler<HTMLInputElement> = (e) => {
    setAddress('')
    setZipCode(e.target.value)
  }

  const handleSubmit: FormEventHandler<HTMLFormElement> = async (e) => {
    e.preventDefault()
    if (!isValidZipCode) return
    const res = await fetch(`/api/search?zipcode=${encodeURI(zipCode)}`)
    if (res.ok) {
      if (res.status === 204) {
        setAddress('存在しない郵便番号です')
      } else {
        const addr = await res.text()
        setAddress(addr)
      }
    } else {
      setAddress('エラーが発生しました')
    }
  }

  return (
    <div>
      <Head>
        <title>Address</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='m-5'>
          <form onSubmit={handleSubmit}>
            <label>
              <span className='mr-2'>郵便番号</span>
              <input
                type='text'
                className='border border-gray-500 rounded'
                onChange={handleChange}
                value={zipCode}
              />
              {!isValidZipCode && (
                <p className='text-red-500 font-semibold'>
                  {validationErrorMessage}
                </p>
              )}
            </label>
          </form>
          <div>
            <p>住所: {address}</p>
          </div>
        </div>
      </main>
    </div>
  )
}
